name: barebones-webserver
version: 0.1.0.0
github: "Katrix/inf329-bareboneshttp-haskell"
license: BSD3
author: "Kathryn Frid"
copyright: "2022 Kathryn Frid"

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6 && < 0.7
  - transformers >= 0.5 && < 0.6
  - mtl >= 2 && < 3
  - unliftio-core >= 0.2.0 && < 0.3
  - lens >= 5 && < 6
  - text >= 1.2 && < 1.3
  - case-insensitive >= 1.2 && < 1.3
  - bytestring >= 0.10 && < 0.11
  - megaparsec >= 9 && < 10
  - network >= 3.1 && < 3.2
  - network-run >= 0.2 && < 0.3
  - nonce >= 1 && < 2
  - time >= 1.9 && < 2

library:
  source-dirs: src

executables:
  barebones-webserver-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - barebones-webserver

tests:
  barebones-webserver-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - barebones-webserver
