name: barebones-webserver
version: 0.1.0.0
github: "Katrix/inf329-bareboneshttp-haskell"
license: BSD3
author: "Kathryn Frid"
copyright: "2022 Kathryn Frid"

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - containers ^>= 0.6
  - transformers ^>= 0.5
  - unliftio-core ^>= 0.2.0
  - unliftio ^>= 0.2.0
  - stm ^>= 2.5
  - mtl ^>= 2.2
  - lens ^>= 5
  - text ^>= 1.2
  - case-insensitive ^>= 1.2
  - bytestring ^>= 0.10
  - megaparsec ^>= 9.2
  - network ^>= 3.1
  - network-run ^>= 0.2
  - nonce ^>= 1.0
  - time ^>= 1.9
  - monad-logger ^>= 0.3
  - directory ^>= 1.3

library:
  source-dirs: src

executables:
  barebones-webserver-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - barebones-webserver

tests:
  barebones-webserver-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - barebones-webserver
